version: "3.9"

services:
  database:
    image: postgres:15
    restart: always
    container_name: shop_postgres
    volumes:
      - ~/.pg/pg_data/shop:/var/lib/posgresql/database
    env_file:
      - .env
  shop:
    build: 
      dockerfile: Dockerfile
      context: .
    image: shop_docker:latest
    container_name: shop_docker
    depends_on:
      - database
    volumes:
      - static_volume:/shop/static
      - media_volume:/shop/media
    env_file:
      - .env
    command: >
      bash -c "python manage.py collectstatic --noinput && python manage.py migrate  && gunicorn -b 0.0.0.0:8000 soaqaz.wsgi:application"
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: shop_nginx
    image: shop_nginx
    volumes:
      - static_volume:/shop/static
      - media_volume:/shop/media
    depends_on:
      - shop
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"


volumes:
  static_volume:
  media_volume: